Add culture filter
vinimichel/Appetite pull request #32
Opened 2023-01-13 11:07 UTC by vinimichel

In diesem PR habe ich die Filter Funktionalität auf unserer Map und Home Activity hinzugefügt. Nun ist es möglich zu entscheiden welche Art von Restaurant man sucht und diese herauszufiltern.

2023-01-13 13:48 UTC, ghost commented
Auch hier leider Konflikte.

2023-01-14 13:45 UTC, vinimichel commented on node_modules/.package-lock.json
> -}
`{
  "lockfileVersion": 3,
  "requires": true,
  "packages": {}
}`

2023-01-14 17:22 UTC, EdidiongJohn commented
Es gibt leider noch Konflikte

2023-01-14 19:35 UTC, smueller74 commented
Bis auf weiteres geschlossen aufgrund von Fehlern beim Konfliktlösen

2023-01-16 21:15 UTC, smueller74 requested changes
Filter funktioniert, aber sowohl echtes Handy als auch Emulator stürzen jetzt ab, wenn ich auf Map oder Reservierungen gehe.

2023-01-17 10:17 UTC, vinimichel commented
@smueller74 Ich glaube das Problem ist nicht beim lösen der Merge Konflikte entstanden sondern schon davor. Ich schaue es mir noch einmal an.

2023-01-17 15:07 UTC, closed without merging